# Site settings
title: bournex
email: bournx@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url: bournex.cn # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  bournex

# Build settings
markdown: kramdown

highlighter: pygments

# Gems
gems: [jekyll-paginate]

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"

coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

#collections:
#  portfolio:
#    output: true
#    permalink: /portfolio/:path/
#  poetry:
#    output: true
#    permalink: /poetry/:path/
